package com.boompala.engine.dailyfortune

import com.boompala.engine.model.FiveElement
import org.junit.Assert.assertEquals
import org.junit.Assert.assertNotEquals
import org.junit.Test

class DailyFortuneRulesTest {

    private val generationCycle = listOf(
        FiveElement.WOOD to FiveElement.FIRE,
        FiveElement.FIRE to FiveElement.EARTH,
        FiveElement.EARTH to FiveElement.METAL,
        FiveElement.METAL to FiveElement.WATER,
        FiveElement.WATER to FiveElement.WOOD,
    )

    private val overcomingCycle = listOf(
        FiveElement.METAL to FiveElement.WOOD,
        FiveElement.WOOD to FiveElement.EARTH,
        FiveElement.EARTH to FiveElement.WATER,
        FiveElement.WATER to FiveElement.FIRE,
        FiveElement.FIRE to FiveElement.METAL,
    )

    @Test
    fun `generating element is complete and consistent`() {
        generationCycle.forEach { (generator, generated) ->
            assertEquals(generator, DailyFortuneRules.elementGenerating(generated))
        }
        // Every element is generated by exactly one element and vice versa.
        assertEquals(
            FiveElement.entries.toSet(),
            FiveElement.entries.map { DailyFortuneRules.elementGenerating(it) }.toSet(),
        )
    }

    @Test
    fun `overcoming element is complete and consistent`() {
        overcomingCycle.forEach { (overcomer, overcome) ->
            assertEquals(overcomer, DailyFortuneRules.elementOvercoming(overcome))
        }
        assertEquals(
            FiveElement.entries.toSet(),
            FiveElement.entries.map { DailyFortuneRules.elementOvercoming(it) }.toSet(),
        )
    }

    @Test
    fun `generating and overcoming partners never coincide`() {
        FiveElement.entries.forEach { element ->
            assertNotEquals(
                DailyFortuneRules.elementGenerating(element),
                DailyFortuneRules.elementOvercoming(element),
            )
        }
    }

    @Test
    fun `five colors cover the conventional element mapping`() {
        assertEquals(FortuneColor.GREEN, DailyFortuneRules.colorFor(FiveElement.WOOD))
        assertEquals(FortuneColor.RED, DailyFortuneRules.colorFor(FiveElement.FIRE))
        assertEquals(FortuneColor.YELLOW, DailyFortuneRules.colorFor(FiveElement.EARTH))
        assertEquals(FortuneColor.WHITE, DailyFortuneRules.colorFor(FiveElement.METAL))
        assertEquals(FortuneColor.BLACK, DailyFortuneRules.colorFor(FiveElement.WATER))
    }

    @Test
    fun `lucky colors derive from the generating element`() {
        assertEquals(FortuneColor.GREEN, DailyFortuneRules.luckyColor(FiveElement.FIRE))
        assertEquals(FortuneColor.WHITE, DailyFortuneRules.luckyColor(FiveElement.WATER))
        assertEquals(FortuneColor.RED, DailyFortuneRules.supportColor(FiveElement.FIRE))
        assertEquals(FortuneColor.BLACK, DailyFortuneRules.avoidColor(FiveElement.FIRE))
    }

    @Test
    fun `lucky numbers are hetu numbers of the generating element`() {
        // 木生火: 木河图数 3/8；金生水: 金河图数 4/9；土生金: 土河图数 5/10。
        assertEquals(listOf(3, 8), DailyFortuneRules.luckyNumbers(FiveElement.FIRE))
        assertEquals(listOf(4, 9), DailyFortuneRules.luckyNumbers(FiveElement.WATER))
        assertEquals(listOf(5, 10), DailyFortuneRules.luckyNumbers(FiveElement.METAL))
        assertEquals(listOf(1, 6), DailyFortuneRules.luckyNumbers(FiveElement.WOOD))
        assertEquals(listOf(2, 7), DailyFortuneRules.luckyNumbers(FiveElement.EARTH))
    }
}
